### ISSUE TITLE
dark/light mode, ui can be made more user friendly, the units for the liquid

### ISSUE THREAD

**Issue by kanikaa-3018** [ajmalrazzaq07/Squarelator#1]
i want to contribute to this project for hacktoberfest2024. please assign me the above issues

**Comment by theajmalrazaq** [comment]
Hi @kanikaa-3018 

Thank you for your interest in contributing to this project for Hacktoberfest 2024! 🎉 I have assigned this issue to you. Feel free to start working on it, and don't hesitate to reach out if you have any questions.

Looking forward to your contribution! 🙌

**Comment by darshitdudhaiya** [comment]
HI @theajmalrazaq ,
I'd like to work on this issue. I believe my skills and i would be a good fit for this task.

Please let me know if I can be assigned to this issue.

**Comment by kanikaa-3018** [comment]
@theajmalrazaq can i pull request or start it from 1st oct?

**Comment by theajmalrazaq** [comment]
Hello @darshitdudhaiya
This task has already been assigned. If you would like to contribute, please look for something else.
Thank you.

**Comment by theajmalrazaq** [comment]
Hey @kanikaa-3018!
First, fork and clone the repo, then make changes and send a pull request. It would be better to start working after October 1st to ensure your contributions count for Hacktoberfest.

**Comment by darshitdudhaiya** [comment]
> Hello @darshitdudhaiya This task has already been assigned. If you would like to contribute, please look for something else. Thank you.


Hello @theajmalrazaq , thank you for the update! I appreciate you letting me know. I'll certainly explore other areas where I can contribute. Looking forward to working on new tasks. Thanks again!

**Comment by kanikaa-3018** [comment]
hey @theajmalrazaq , on the official website it is showing that this is not part of the hacktoberfest unless there is a lable of hacktoberfest-accepted on the official site, could you please look into it, as my PR wasnt counted towards the contributions. Thanks again!

**Comment by theajmalrazaq** [comment]
> Hey @theajmalrazaq, on the official website it is showing that this is not part of Hacktoberfest unless there is a label of `hacktoberfest-accepted` on the official site. Could you please look into it, as my PR wasn't counted towards the contributions. Thanks again!

Hey @kanikaa-3018!  
The `hacktoberfest-accepted` label will be added when I merge your code after a successful review. Once it's merged, it will be counted. I've also added a comment on your pull request, so please check that! 😊

**Comment by kanikaa-3018** [comment]
okay sir, ill look into it
