### ISSUE TITLE
Fix Count Button Functionality and Add Currency Selection When Count is Clicked

### ISSUE THREAD

**Issue by theajmalrazaq** [ajmalrazzaq07/Squarelator#12]
When a price is added and the "Count" button is clicked, the calculation does not work. 

**Tasks:**

1. Fix the functionality of the "Count" button to ensure it works correctly when a price is entered.
2. Add a currency selection option that allows users to choose their preferred currency before calculating the total.

**Comment by aparna-u** [comment]
Hi, Please assign this issue to me

**Comment by theajmalrazaq** [comment]
Hey @aparna-u, I've assigned this task to you!

**Comment by aparna-u** [comment]
Hi @theajmalrazaq , I've implemented the currency dropdown and fixed the count button functionality. Please take a look at PR #13  and let me know if you have any suggestions.
