### ISSUE TITLE
Feature: Add export as PDF option

### ISSUE THREAD

**Issue by sp9324** [ajmalrazzaq07/Squarelator#16]
I would like to add "export as PDF" option. Kindly assign this issue to me, @theajmalrazaq

**Comment by theajmalrazaq** [comment]
@sp9324 Hey, when the user does calculations, add an export option next to the close button.

**Comment by sp9324** [comment]
> @sp9324 Hey, when the user does calculations, add an export option next to the close button.

could you specify exactly which close button you mean?

**Comment by theajmalrazaq** [comment]
![Screenshot_20241011_183322_Chrome.jpg](https://github.com/user-attachments/assets/f0524ca1-b098-4de8-a8cb-8b1b25987ca7)

Beside this one.

**Comment by sp9324** [comment]
> ![Screenshot_20241011_183322_Chrome.jpg](https://private-user-images.githubusercontent.com/127989125/375772533-f0524ca1-b098-4de8-a8cb-8b1b25987ca7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NTUyNTIsIm5iZiI6MTcyODY1NDk1MiwicGF0aCI6Ii8xMjc5ODkxMjUvMzc1NzcyNTMzLWYwNTI0Y2ExLWIwOTgtNGRlOC1hOGNiLThiMWIyNTk4N2NhNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQxMzU1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjg5OTQ3Mzk4NjU3OTNlNmQ2MGNmYTQ1MmI1OWQyYjY1Njc1YzgwM2Y2Mzk5NWE5NDM0NmU4OGRmNDYxZGU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.r-GGDTUVdB9X98yXxmEhWKGfJE3UTxYc2VFwO37GMW0)
> 
> Beside this one.

Done.

https://github.com/user-attachments/assets/39624a33-76f2-4b2d-9840-dd590219df56
