### ISSUE TITLE
Adding note to the items

### ISSUE THREAD

**Issue by mohtasheem135** [ajmalrazzaq07/Squarelator#18]
It would be really great if we can add some notes to the added items. 

We can give option to the user to add short notes(one or two words) or detailed notes( one or two sentence). We will show the short note on the added list and the detailed note will be hidden. 

This could be very helpful for the users for easy management. 

Please assign me this task and add hactoberfest label and gssoc-extd label.

**Comment by theajmalrazaq** [comment]
@mohtasheem135 You are good to go bro!
