### ISSUE TITLE
Add Feature: Export Data or Report as PDF

### ISSUE THREAD

**Issue by darshitdudhaiya** [ajmalrazzaq07/Squarelator#20]
Currently, Your application provides users with the ability to view and manage data as well as export data as json file. To enhance usability and provide more value to your users, we should implement a feature that allows exporting data or reports in PDF format.

**Comment by darshitdudhaiya** [comment]
@theajmalrazaq assign this issue to me, as I would like to work on adding this feature.

**Comment by theajmalrazaq** [comment]
@darshitdudhaiya This feature is already implemented!

**Comment by theajmalrazaq** [comment]
@darshitdudhaiya you can proper format pdf like invoice while - export as pdf

**Comment by darshitdudhaiya** [comment]
Ok, I will do it. @theajmalrazaq
