### ISSUE TITLE
PDF contents are barely visible

### ISSUE THREAD

**Issue by surajb0710** [ajmalrazzaq07/Squarelator#22]
Issue : 
PDF contents are not visible

Expected Behavior : 
The content should be easily visible.

Are you interested to contribute to this issue? 
No

[report.pdf](https://github.com/user-attachments/files/17389131/report.pdf)

**Comment by Raja-Muhammad-Bilal-Arshad** [comment]
> Issue : PDF contents are not visible
> 
> Expected Behavior : The content should be easily visible.
> 
> Are you interested to contribute to this issue? 
> YES
> [report.pdf](https://github.com/user-attachments/files/17389131/report.pdf)


Brother I can help you with this issue.. Some simple solutions.. are PDF.js 
and bhai, you can also use.... Embed Tag: Using the <embed> or <iframe> HTML tags to display the PDF.
I also have some other solutions also .... if you are interesting do let me know....

**Comment by surajb0710** [comment]
Hi,

I came across this project by chance and noticed a bug, so I raised the issue to help improve it.

Feel free to take it from here.

Thanks for your inputs.
