### ISSUE TITLE
Enhance a proper Readme file that clearly depicts the project, folder structure, how to contribute etc., 

### ISSUE THREAD

**Issue by Prakash-Ravichandran** [ajmalrazzaq07/Squarelator#3]
@theajmalrazaq 

please assign this to me Ajmal, i would like to contribute to your project.

**Comment by theajmalrazaq** [comment]
Hi @Prakash-Ravichandran 
Thank you for your interest in contributing! I've assigned the issue to you. Feel free to enhance the README and also add CONTRIBUTING.md with details on the project description, folder structure, and contribution guidelines. If you need any specific information or have any questions, don't hesitate to reach out.

Looking forward to your contributions!

**Comment by theajmalrazaq** [comment]
@Prakash-Ravichandran  Hey!!
Are You working on this task??

**Comment by Cormwww** [comment]
Hello could I be assigned this project?

**Comment by theajmalrazaq** [comment]
Hi @Cormwww !
Thank you for your interest in contributing! I've assigned the issue to you. Feel free to enhance the README and also add CONTRIBUTING.md with details on the project description, folder structure, and contribution guidelines. If you need any specific information or have any questions, don't hesitate to reach out.

Looking forward to your contributions!

**Comment by biswajit-sarkar-007** [comment]
Hi, I'm interested in solving this. Can I be assigned?

**Comment by Prakash-Ravichandran** [comment]
@theajmalrazaq i was working on this one, why it was reassigned to someother person

**Comment by theajmalrazaq** [comment]
@Prakash-Ravichandran I assigned the task to him/her since you didn't respond. 
No worries, you  both can contribute.

**Comment by Prakash-Ravichandran** [comment]
@theajmalrazaq sure, will raise a PR tomorrow.

**Comment by theajmalrazaq** [comment]
@Prakash-Ravichandran  Are you working on it??
