### ISSUE TITLE
Import or export file

### ISSUE THREAD

**Issue by Sauhard74** [ajmalrazzaq07/Squarelator#4]
Import /Export file:
being a notfier app it is very useful to track down your history and your tasks so I think this can be a great addition

**Comment by theajmalrazaq** [comment]
Hey @Sauhard74 
Would you like to work on this task?

**Comment by Sauhard74** [comment]
Yes i would love to

**Comment by theajmalrazaq** [comment]
i have assigned it to you!

**Comment by theajmalrazaq** [comment]
@Sauhard74  Hey!
Are you working on this issue??

**Comment by Sauhard74** [comment]
Yess I am almost done solving the issue I will be raising the pr tommorow

**Comment by Sauhard74** [comment]
can you see to the pr i made , I enabled the two buttons and they are working ,also I maintained the blue box theme for the buttons , can you merge the pr soon? it would be really helpful for me
