### ISSUE TITLE
Add Dark Mode Theme and Basic Animations

### ISSUE THREAD

**Issue by ankit071105** [ajmalrazzaq07/Squarelator#6]
# Description
We need to implement a dark mode theme to improve user experience, especially in low-light environments. Additionally, basic animations will be added to enhance the user interface's responsiveness and interactivity.

# Tasks:
Dark Mode Theme:

Create a toggle button to switch between light mode and dark mode.
Define a dark mode color palette (background, text, buttons, etc.).
Apply the dark mode styles using CSS variables for easy theming.
Store the user's theme preference using localStorage to persist across sessions.
Basic Animations:

Add smooth transitions for the dark mode toggle (fade in/out effects).
Implement basic animations on hover for buttons, links, and other interactive elements (e.g., scaling or color changes).
Ensure animations are smooth and do not affect page performance.
# Technologies:
CSS: For theme styles and animations (e.g., @keyframes, transform, transition).
JavaScript: For handling the dark mode toggle and persisting user preferences using localStorage.
# Expected Outcome:
A fully functional dark mode theme toggle.
Smooth, subtle animations that enhance user interaction.

**Comment by theajmalrazaq** [comment]
@ankit071105  
Thank you for your interest! The same issue has already been assigned to someone else—you can check the **Issues** tab. However, there are more areas where you can contribute.  
Regards!

**Comment by theajmalrazaq** [comment]
@ankit071105  
Additionally, if you're interested, you can work on animations and transitions.

**Comment by ankit071105** [comment]
> @ankit071105 Additionally, if you're interested, you can work on animations and transitions.

okay i can create a pull request regarding the animations
