### ISSUE TITLE
Fix UI - Make Mobile First,remove navbar,fix dark mode color scheme,implement dark mode with local storage

### ISSUE THREAD

**Issue by theajmalrazaq** [ajmalrazzaq07/Squarelator#9]
**Mobile-First Design:**
Refactor the UI components to ensure they are optimized for mobile devices first.
Test the design on various screen sizes to guarantee a seamless experience.

**Remove Navigation Bar**:
Identify the existing navigation bar and remove it from the layout.
Ensure that the application remains navigable without the navbar.

**Fix Dark Mode Color Scheme:**
Review the current dark mode color scheme and make necessary adjustments for better visibility and aesthetics.
Ensure that text and background colors provide sufficient contrast.
Implement Dark Mode with Local Storage:

Add functionality to toggle dark mode on and off.
Utilize local storage to save the user's preference for dark mode, ensuring that their choice persists across sessions.

**Comment by darshitdudhaiya** [comment]
HI @theajmalrazaq ,
I'd like to work on this issue. I believe my skills and i would be a good fit for this task.

Please let me know if I can be assigned to this issue.

**Comment by theajmalrazaq** [comment]
Hey @darshitdudhaiya!  
I've assigned this to you. Please fix all the UI issues for your pull request to be accepted.

**Comment by darshitdudhaiya** [comment]
@theajmalrazaq, I just wanted to know if you agree with adding Bootstrap or Tailwind for styling, and if I should also refactor this code to improve indentation.

**Comment by theajmalrazaq** [comment]
@darshitdudhaiya Yes, feel free to add any improvements you'd like, but please keep the color scheme and logo unchanged.

**Comment by darshitdudhaiya** [comment]
@theajmalrazaq, thank you for allowing me to proceed with it.
